Fix file

diff --git a/.github/workflows/frontend-cd.yaml b/.github/workflows/frontend-cd.yaml
--- a/.github/workflows/frontend-cd.yaml
+++ b/.github/workflows/frontend-cd.yaml
@@ -79,7 +79,7 @@ jobs:
       run: |
         cd starter/frontend  # Change directory to the frontend directory
         CI=true npm test  # Run tests with CI environment variable set to true
-        
+
   build:  # Job for building and deploying the application
     runs-on: ubuntu-latest  # Execute on the latest version of Ubuntu
     needs: [lint, test]  # This ensures 'build' only runs if 'lint' and 'test' jobs succeed
@@ -123,14 +123,14 @@ jobs:
         docker push 633011985446.dkr.ecr.us-east-1.amazonaws.com/frontend:latest  # Push Docker image to ECR
 
     - name: Check if Docker image is uploaded to ECR
-        run: |
-          # Check if the Docker image exists in ECR
-          if aws ecr describe-images --repository-name frontend | grep -q "imageTag\": \"latest\""; then
-            echo "Docker image uploaded to ECR"
-          else
-            echo "Docker image not uploaded to ECR, failing pipeline"
-            exit 1
-          fi
+    run: |
+      # Check if the Docker image exists in ECR
+      if aws ecr describe-images --repository-name frontend | grep -q "imageTag\": \"latest\""; then
+        echo "Docker image uploaded to ECR"
+      else
+        echo "Docker image not uploaded to ECR, failing pipeline"
+        exit 1
+      fi
           
     - name: Install kubectl  # Step to install kubectl
     run: |  # Define the shell command to be executed
